### ISSUE TITLE
when reading checkpoint file tensorflow.python.framework.errors_impl.OutOfRangeError

### ISSUE THREAD

**Issue by akashdexati** [taki0112/UGATIT#59]
Hi @taki0112 
When reading the checkpoint file **_selfie2anime(100 epoch);_**  I get tensorflow.python.framework.errors_impl.OutOfRangeError.
The tensorflow version I am using is 1.14.0.
Can you please guide me on the issue.

Below are the logs for your reference.

```
 [*] Reading checkpoints...
W0821 04:54:22.281598 140669784717120 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-08-21 04:54:22.506653: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Out of range: Read less bytes than requested
Traceback (most recent call last):
  File "main.py", line 112, in <module>
    main(imgname)
  File "main.py", line 102, in main
    gan.test()
  File "/home/ubuntu/UGATIT/UGATIT.py", line 620, in test
    could_load, checkpoint_counter = self.load(self.checkpoint_dir)
  File "/home/ubuntu/UGATIT/UGATIT.py", line 606, in load
    self.saver.restore(self.sess, os.path.join(checkpoint_dir, ckpt_name))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1286, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested
	 [[node save/RestoreV2 (defined at /home/ubuntu/UGATIT/UGATIT.py:619) ]]

Original stack trace for u'save/RestoreV2':
  File "main.py", line 112, in <module>
    main(imgname)
  File "main.py", line 102, in main
    gan.test()
  File "/home/ubuntu/UGATIT/UGATIT.py", line 619, in test
    self.saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by kikacaty** [comment]
I got the same error here.

**Comment by xiaotaw** [comment]
check if u got the ckpt files complete.

**Comment by kikacaty** [comment]
@akashdexati I resolved the issue by downloading and unziping the pretrained model on a MACOS.

**Comment by kumardexati** [comment]
@kikacaty What version of Tensorflow are you using?

**Comment by ColorfulGhost** [comment]
I got the same error here.

CUDA version?
tf version?

**Comment by FantasyJXF** [comment]
Met the same problem with Google Colab with GPU/Python3

**Comment by zhiji666** [comment]
I resolved the error by removing file "checkpoint" in folder "UGATIT_selfie2anime_lsgan_4resblock_6dis_1_1_10_10_1000_sn_smoothing".

**Comment by FantasyJXF** [comment]
@akashdexati  @kikacaty  After you unzip the checkpoint file, you should have a directory named **checkpoint** which is about 8G Bytes, use the default compress APP on MAC would help.

**Comment by emtelGNR** [comment]
well , bro ,I just met the same problem , have you slove it?   py3.6+tf1.14
![2020-08-07 18-43-46屏幕截图](https://user-images.githubusercontent.com/48984931/89638176-f3549480-d8dd-11ea-9504-02b6dd9fc0f6.png)

**Comment by SMY19999** [comment]
看了大家的讨论，原因应该是解压的时候，ckpt文件损坏了，换一个系统来解压，就好了。
